# Site
name: '4ss.org'
description: '科技新知分享'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
disqus: ''
email: '1417400@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Gitgle:
      name:           Gitgle
      site:           https://gitgle.github.io/
      avatar:         'assets/images/logo.png'
      bio:            "科技新知分享 - 4ss.org"
      email:          1417400@gmail.com
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Gitgle
      avatar: 'assets/images/logo.png'
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
